# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Torch < Formula
  desc "Keep your secrets safe"
  homepage "https://github.com/torchsecurity/torch-secret-analyzer"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/torchsecurity/torch-secret-analyzer/releases/download/v0.1.0/torch_0.1.0_darwin_amd64.tar.gz"
      sha256 "86f32ca8b93d38d7806c601d3c605c9bf9e4fcfe9a5bab1f44306a1c8fa9e041"

      def install
        bin.install "torch"
      end
    end
    on_arm do
      url "https://github.com/torchsecurity/torch-secret-analyzer/releases/download/v0.1.0/torch_0.1.0_darwin_arm64.tar.gz"
      sha256 "1ab3511ec6c499d52d36d96156071dfcd3552fb85b6172dfa583a8f6013ae52d"

      def install
        bin.install "torch"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/torchsecurity/torch-secret-analyzer/releases/download/v0.1.0/torch_0.1.0_linux_amd64.tar.gz"
        sha256 "11b6b4a690438c94d592fcb8c337c6942deb74d809bc04f329a19644d0ed61c6"

        def install
          bin.install "torch"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/torchsecurity/torch-secret-analyzer/releases/download/v0.1.0/torch_0.1.0_linux_arm64.tar.gz"
        sha256 "08738157f973e5e5b7e9804aea36ac5fe76d0a1398735aa8bed2e4e4df8d2dbf"

        def install
          bin.install "torch"
        end
      end
    end
  end

  test do
    system "#{bin}/torch --version"
  end
end
