# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Torch < Formula
  desc "Keep your secrets safe"
  homepage "https://github.com/torchsecurity/torch-secret-analyzer"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/torchsecurity/torch-secret-analyzer/releases/download/v0.1.0/torch_0.1.0_darwin_amd64.tar.gz"
      sha256 "d9cf16f1db2377f3f176b7b6425ae803ab410d484cb7de4636f4f4bd4789d9bc"

      def install
        bin.install "torch"
      end
    end
    on_arm do
      url "https://github.com/torchsecurity/torch-secret-analyzer/releases/download/v0.1.0/torch_0.1.0_darwin_arm64.tar.gz"
      sha256 "118d924c9f462a854434b44eae0d4a583832261e210b6790dce888fccd1c7f07"

      def install
        bin.install "torch"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/torchsecurity/torch-secret-analyzer/releases/download/v0.1.0/torch_0.1.0_linux_amd64.tar.gz"
        sha256 "15f3c3f49ee1f09aac46683cac6a35a82bce53156cb1666c9fde326b4221598f"

        def install
          bin.install "torch"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/torchsecurity/torch-secret-analyzer/releases/download/v0.1.0/torch_0.1.0_linux_arm64.tar.gz"
        sha256 "f120a47506171fbbe11137e0826b09316299c1fcd7251b0d6205a6d8e1556746"

        def install
          bin.install "torch"
        end
      end
    end
  end

  test do
    system "#{bin}/torch --version"
  end
end
