# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Torch < Formula
  desc "Keep your secrets safe"
  homepage "https://github.com/torchsecurity/torch-secret-analyzer"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/torchsecurity/torch-secret-analyzer/releases/download/v0.1.0/torch_0.1.0_darwin_amd64.tar.gz"
      sha256 "298c2b4cd31c83453e9584e807842de8cd170416796677f6f4e0d3ca55dfcc78"

      def install
        bin.install "torch"
      end
    end
    on_arm do
      url "https://github.com/torchsecurity/torch-secret-analyzer/releases/download/v0.1.0/torch_0.1.0_darwin_arm64.tar.gz"
      sha256 "576569fe14ccbb065bb17bf8299ce7be78b261fa665a101817de9af4ffd6b847"

      def install
        bin.install "torch"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/torchsecurity/torch-secret-analyzer/releases/download/v0.1.0/torch_0.1.0_linux_amd64.tar.gz"
        sha256 "74366153b791f6528b649ec97a7a990da28483345cc00affb4f46dc5c073641a"

        def install
          bin.install "torch"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/torchsecurity/torch-secret-analyzer/releases/download/v0.1.0/torch_0.1.0_linux_arm64.tar.gz"
        sha256 "626785cfe3f43cdeeda3eda96e9c0c0563e860232d7e42b4a60955dd0b492766"

        def install
          bin.install "torch"
        end
      end
    end
  end

  test do
    system "#{bin}/torch --version"
  end
end
